In [1]:
import numpy
numpy.__version__

'1.19.2'

In [2]:
import numpy as np

In [3]:
np?

In [4]:
# 파이썬의 리스트는 유연하여 서로 다른 타입의 데이터를 리스트에 담을 수 있다
L = [True, "2", 3.0,4]
[type(item) for item in L]

[bool, str, float, int]

In [5]:
#파이썬의 고정 타입 배열
import array
L = list(range(10))
A = array.array('i' , L)
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
#파이썬 리스트에서 배열 만들기

# 넘파이의 배열의 모든 요소는 같은 타입이다. 타입이 일치하지 않으면 상위 타입을 취하게 된다.
A1 = np.array([1,4,2,5,3])
A2 = np.array([3.14, 4,2, 3])
print(f'A1 = {A1},\nA2 = {A2}')

# 배열의 데이터 타입을 결정해주려면 dtype키워드를 사용
A3 = np.array([1,2,3,4], dtype = 'float32')
print(f'A3 = {A3}')

#리스트를 중첩하면 다차원 배열이 된다
A4 = np.array([range(i,i+3) for i in [2,4,6]])
print(f'A4 = {A4}')


A1 = [1 4 2 5 3],
A2 = [3.14 4.   2.   3.  ]
A3 = [1. 2. 3. 4.]
A4 = [[2 3 4]
 [4 5 6]
 [6 7 8]]


In [7]:
#처음부터 배열 만들기

#0으로 채운 길이 10의 정수 배열
np.zeros(10, dtype=int)

# 1로 채운 3x5 부동 소수점 배열
np.ones((3,5), dtype=float)

# 3.14로 채운 3x5 배열
np.full((3,5), 3.14)

# 0에서 2씩 더하여 20까지 채운 배열
np.arange(0,21,2)

# 0과 1 사이에 일정한 간격을 가진 다섯 개의 값으로 채운 배열
np.linspace(0,1,5)

# 균등하게 분포된 3x3배열 , 0과 1사이의 난수
np.random.random((3,3))

# 표준정규분포를 따르는 난수로 채운 3x3 배열
np.random.normal(0,1,(3,3))

# 0,10 구간의 임의의 정수로 채운 3x3배열 만들기
np.random.randint(0,10,(3,3))

# 3x3 단위 행렬
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [8]:
# numpy 표준 데이터 타입 bool, int, uint, float, complex

np.zeros(10, dtype="int16")
np.zeros(10, dtype=np.int16)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

In [9]:
# numpy 배열의 기초

#배열 속성 지정

#1차원 ~ 3차원 배열
x1 = np.random.randint(10, size=6) 
x2 = np.random.randint(10, size=(3,4)) 
x3 = np.random.randint(10, size=(3,4,5)) 

#배열의 속성
print("x3 ndim : ",x3.ndim)
print("x3 shape :",x3.shape)
print("x3 size : ",x3.size)
print("x3 dtype : ",x3.dtype)
print(f'x3 item size : {x3.itemsize} bytes')
print(f'x3 nbytes : {x3.nbytes} bytes')

x3 ndim :  3
x3 shape : (3, 4, 5)
x3 size :  60
x3 dtype :  int64
x3 item size : 8 bytes
x3 nbytes : 480 bytes


In [10]:
# 배열 인덱싱
x1[0]
x1[-1]

x2[0,1]
x2[0,-3]
x2[0,0] = 12 
x2[0,0]

# 주의할점 : 넘파이의 배열은 고정 타입을 갖으므로 정수배열에 부동소수점 값을 집어 넣으면 소숫점 이하를 잘라버림
x1[1] = 3.141592
x1[1]

3

In [21]:
# 배열 슬라이싱 : 하위 배열에 접근하기
# x[start:stop:step]

x = np.arange(10)
x[:5]
x[5:]
x[4:7]
x[::2]
x[1::2]
x[::-1]
x[5::-2]

print(x2)
x2[:2,:3] # 2개의 행 3개의 열
x2[:,::2] # 한 열 걸러 하나씩
x2[::-1,::-1]

x2[:,0] # x2의 첫번째 열
x2[0,:] # x2의 첫번째 행

[[12  4  1  1]
 [ 1  6  7  0]
 [ 5  0  0  2]]


array([12,  4,  1,  1])

In [34]:
# 사본이 아닌 뷰로서의 하위 배열
# 배열 슬라이스가 배열 데이터의 사본이 아니라 뷰로 반환한다 따라서 사본을 만들기 위해서는 함수 copy를 이용
x2_sub = x2[:2,:2]
x2_sub[0,0] = 99 # x2_sub의 원소를 변경하면 x2도 변경됨
x2

x2_sub_copy = x2[:2,2:].copy()
x2_sub_copy[0,0] = 42 #x2_sub_copy의 원소를 변경하면 x2는 변경이 안됨
x2

array([[99,  4,  1,  1],
       [ 1,  6,  7,  0],
       [ 5,  0,  0,  2]])

In [45]:
# 배열 재구조화
grid = np.arange(1,10).reshape(3,3)
print(grid)

x = np.array([1,2,3])
x.reshape((1,3)) ; x[np.newaxis, : ]  # reshape를 이용한 방법과 newaxis를 이용한 방법
x.reshape((3,1)) ; x[ :, np.newaxis]  # reshape를 이용한 방법과 newaxis를 이용한 방법

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[1],
       [2],
       [3]])

In [55]:
# 배열 연결

# 연결 np.concatenate : 튜플이나 배열의 리스트를 첫 번째 인수로 취함
x = np.array([1,2,3])
y = np.array([3,2,1])
np.concatenate([x,y])

z = np.array([99,99,99])
np.concatenate([x,y,z])

grid = np.array([[1,2,3],
                [4,5,6]])

np.concatenate([grid,grid]) # 첫 번째 축을 따라 연결
np.concatenate([grid,grid], axis=1) # 두 번째 축을 따라 연결 (0부터 시작하는 인덱스 방식)

# np.vstack (수직 스택)
x = np.array([1,2,3])
grid = np.array([[9,8,7],
                 [6,5,4]])
np.vstack([x,grid])

# np.hstack (수평 스택) 
y = np.array([[99],
              [99]])
np.hstack([grid,y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

In [73]:
# 배열 분할

# np.split(x, 분할 지점)
x = [1,2,3,99,99,3,2,1]
x1 , x2 , x3 = np.split(x,[3,5])  
print(x1,x2,x3)

# np.hsplit, np.vsplit
grid = np.arange(16).reshape((4,4))

upper , lower = np.vsplit(grid,[2])
print(upper)
print(lower)

left , right = np.hsplit(gird,[2])
print(left)
print(right)

[1 2 3] [99 99] [3 2 1]
[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]
[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
