In [1]:
name = ['Alice', 'Bob', 'Cathy', 'Doug']
age = [25, 45, 37, 19]
weight = [55.0, 88.5, 68.0, 61.5]

In [6]:
# 구조화된 배열을 위한 복합 데이터 타입 (딕셔너리 방식)
import numpy as np
data = np.zeros(4, dtype={'names':('name','age','weight'),
                          'formats':('U10','i4','f8')})
data['name'] = name
data['age'] = age
data['weight'] = weight
data

array([('Alice', 25, 55. ), ('Bob', 45, 88.5), ('Cathy', 37, 68. ),
       ('Doug', 19, 61.5)],
      dtype=[('name', '<U10'), ('age', '<i4'), ('weight', '<f8')])

In [10]:
data['name']
data[0]
data[-1]['name']
#나이가 30 이하인 이름 가져오기
data[data['age']<30]['name']

array(['Alice', 'Doug'], dtype='<U10')

In [12]:
# 고급 복합 타입 (mat 컴포넌트)
tp = np.dtype([('id','i8'),('mat','f8',(3,3))])
X = np.zeros(1, dtype=tp)
print(X[0])
print(X['mat'][0])

(0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]])
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
