In [8]:
import numpy as np

# 루프는 느리다.

def compute_reciprocals(Values):
    output = np.empty(len(Values))
    for i in range(len(Values)):
        output[i] = 1.0 / Values[i]
    return output

Values = np.random.randint(1,10, size=5)
compute_reciprocals(Values)

array([0.25      , 0.125     , 0.33333333, 0.33333333, 0.125     ])

In [9]:
#100만번 연산의 속도
big_array = np.random.randint(1,100, size=1000000)
%timeit compute_reciprocals(big_array)

1.53 s ± 9.99 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [11]:
# UFuncs
print(compute_reciprocals(values))
print(1.0 / values)

[0.16666667 0.11111111 0.25       0.33333333 0.11111111]
[0.16666667 0.11111111 0.25       0.33333333 0.11111111]


In [12]:
%timeit (1.0 / big_array) # 파이썬 루프보다 수백 배 빠른 속도로 작업을 완료함

609 µs ± 2.48 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [17]:
# 두 배열간의 연산 및 다차원 베열에서도 동작
print(np.arange(5) / np.arange(1,6))

x = np.arange(9).reshape(3,3)
(2**x)

[0.         0.5        0.66666667 0.75       0.8       ]


array([[  1,   2,   4],
       [  8,  16,  32],
       [ 64, 128, 256]])

In [22]:
# ufuncf를 통한 백터화 연산은 파이썬 루프를 통해 구현된 연산보다 효율적임!

#배열 산술 연산 : 사칙연산 가능
x = np.arange(4)
print("x       = ",x)
print("x  +  2 = ",x + 2)  # np.add
print("x  -  2 = ",x - 2)  # np.subtract
print("x  *  2 = ",x * 2)  # np.multiply
print("x  /  2 = ",x / 2)  # np.divide
print("x //  2 = ",x // 2) # np.floor_divide
print("-x       = ",-x)    # np.negative
print("x **  2 = ",x ** 2) # np.power
print("x  %  2 = ",x % 2)  # np.mod

x       =  [0 1 2 3]
x  +  2 =  [2 3 4 5]
x  -  2 =  [-2 -1  0  1]
x  *  2 =  [0 2 4 6]
x  /  2 =  [0.  0.5 1.  1.5]
x //  2 =  [0 0 1 1]
-x       =  [ 0 -1 -2 -3]
x **  2 =  [0 1 4 9]
x  %  2 =  [0 1 0 1]


In [37]:
# 절댓값 함수
x = np.array([-2, -1, 0, 1, 2])
print(np.abs(x))
y = np.array([3 - 4j, 4 - 3j, 2 + 0j, 0 + 1j]) # 복소수의 경우 크기를 반환
print(np.abs(y))

# 삼각함수
theta = np.linspace(0, np.pi, 3)
print(f'theta = {theta}')
print(f'sin = {np.sin(theta)}')
print(f'cos = {np.cos(theta)}')
print(f'tan = {np.tan(theta)}')

x = [-1,0,1] #
print(f'arcsin = {np.arcsin(x)}')
print(f'arccos = {np.arccos(x)}')
print(f'arctan = {np.arctan(x)}')

# 위 값들은 기계 정밀도 내에서 계산되어 0이어야 하는 값이 언제나 0이 되지는 않는다

[2 1 0 1 2]
[5. 5. 2. 1.]
theta = [0.         1.57079633 3.14159265]
sin = [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos = [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan = [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]
arcsin = [-1.57079633  0.          1.57079633]
arccos = [3.14159265 1.57079633 0.        ]
arctan = [-0.78539816  0.          0.78539816]


In [45]:
# 지수와 로그
x = [1, 2, 3]
print(f'exp : {np.exp(x)}') # np.expm1(x)의 경우 정확도가 더 큼
print(f'2^x : {np.power(2,x)}')

y = [1,2,4,10]
print(f'ln(y) = {np.log(y)}') # np.lig1p(qy)의 경우 정확도가 더 큼
print(f'log2(y) = {np.log2(y)}')
print(f'log10(y) = {np.log10(y)}')

exp : [ 2.71828183  7.3890561  20.08553692]
2^x : [2 4 8]
ln(y) = [0.         0.69314718 1.38629436 2.30258509]
log2(y) = [0.         1.         2.         3.32192809]
log10(y) = [0.         0.30103    0.60205999 1.        ]


In [48]:
# 특화된 유니버셜 함수
from scipy import special
x = [1, 5, 10]
special.gamma(x) #감마 함수
special.gammaln(x)
special.beta(x,2) # 베타 함수
special.erf(x) #가우스 적분

array([0.84270079, 1.        , 1.        ])

In [55]:
# 출력 지정
x = np.arange(5)
y = np.empty(5)
np.multiply(x, 10, out=y)
print(y)

z = np.zeros(10)
np.power(2,x, out=z[::2])
print(z)

[ 0. 10. 20. 30. 40.]
[ 1.  0.  2.  0.  4.  0.  8.  0. 16.  0.]


In [62]:
# 집계

# 누적된 연산을 하려면 reduce
x = np.arange(1,6)
np.add.reduce(x) # 1~5를 더함
np.multiply.reduce(x) #1~5를 곱합

#계산의 중간과정을 저장하고 싶다면 accumulate
np.add.accumulate(x)
np.multiply.accumulate(x)

#외적 outer
x = np.arange(1,6)
np.multiply.outer(x,x)


array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])